//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ws2811_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ws2811_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ws2811_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ws2811_t() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          rpi_ws281xPINVOKE.delete_ws2811_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ulong render_wait_time {
    set {
      rpi_ws281xPINVOKE.ws2811_t_render_wait_time_set(swigCPtr, value);
    } 
    get {
      ulong ret = rpi_ws281xPINVOKE.ws2811_t_render_wait_time_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_ws2811_device device {
    set {
      rpi_ws281xPINVOKE.ws2811_t_device_set(swigCPtr, SWIGTYPE_p_ws2811_device.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = rpi_ws281xPINVOKE.ws2811_t_device_get(swigCPtr);
      SWIGTYPE_p_ws2811_device ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ws2811_device(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_rpi_hw_t rpi_hw {
    set {
      rpi_ws281xPINVOKE.ws2811_t_rpi_hw_set(swigCPtr, SWIGTYPE_p_rpi_hw_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = rpi_ws281xPINVOKE.ws2811_t_rpi_hw_get(swigCPtr);
      SWIGTYPE_p_rpi_hw_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_rpi_hw_t(cPtr, false);
      return ret;
    } 
  }

  public uint freq {
    set {
      rpi_ws281xPINVOKE.ws2811_t_freq_set(swigCPtr, value);
    } 
    get {
      uint ret = rpi_ws281xPINVOKE.ws2811_t_freq_get(swigCPtr);
      return ret;
    } 
  }

  public int dmanum {
    set {
      rpi_ws281xPINVOKE.ws2811_t_dmanum_set(swigCPtr, value);
    } 
    get {
      int ret = rpi_ws281xPINVOKE.ws2811_t_dmanum_get(swigCPtr);
      return ret;
    } 
  }

  public ws2811_channel_t channel {
    set {
      rpi_ws281xPINVOKE.ws2811_t_channel_set(swigCPtr, ws2811_channel_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = rpi_ws281xPINVOKE.ws2811_t_channel_get(swigCPtr);
      ws2811_channel_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ws2811_channel_t(cPtr, false);
      return ret;
    } 
  }

  public ws2811_t() : this(rpi_ws281xPINVOKE.new_ws2811_t(), true) {
  }

}
