/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_rpi_ws281x(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_rpi_ws281x(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_rpi_ws281x(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


#include <stdint.h>		// Use the C99 official header


#include "ws2811.h"


    uint32_t ws2811_led_get(ws2811_channel_t *channel, int lednum)
    {
        if (lednum >= channel->count)
        {
            return -1;
        }

        return channel->leds[lednum];
    }

    int ws2811_led_set(ws2811_channel_t *channel, int lednum, uint32_t color)
    {
        if (lednum >= channel->count)
        {
            return -1;
        }

        channel->leds[lednum] = color;

        return 0;
    }

    ws2811_channel_t *ws2811_channel_get(ws2811_t *ws, int channelnum)
    {
        return &ws->channel[channelnum];
    }


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT int SWIGSTDCALL CSharp_WS2811_TARGET_FREQ_get() {
  int jresult ;
  int result;
  
  result = (int)(800000);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_SK6812_STRIP_RGBW_get() {
  int jresult ;
  int result;
  
  result = (int)(0x18100800);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_SK6812_STRIP_RBGW_get() {
  int jresult ;
  int result;
  
  result = (int)(0x18100008);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_SK6812_STRIP_GRBW_get() {
  int jresult ;
  int result;
  
  result = (int)(0x18081000);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_SK6812_STRIP_GBRW_get() {
  int jresult ;
  int result;
  
  result = (int)(0x18080010);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_SK6812_STRIP_BRGW_get() {
  int jresult ;
  int result;
  
  result = (int)(0x18001008);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_SK6812_STRIP_BGRW_get() {
  int jresult ;
  int result;
  
  result = (int)(0x18000810);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_SK6812_SHIFT_WMASK_get() {
  int jresult ;
  int result;
  
  result = (int)(0xf0000000);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_WS2811_STRIP_RGB_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00100800);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_WS2811_STRIP_RBG_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00100008);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_WS2811_STRIP_GRB_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00081000);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_WS2811_STRIP_GBR_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00080010);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_WS2811_STRIP_BRG_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00001008);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_WS2811_STRIP_BGR_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00000810);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_WS2812_STRIP_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00081000);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_SK6812_STRIP_get() {
  int jresult ;
  int result;
  
  result = (int)(0x00081000);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_SK6812W_STRIP_get() {
  int jresult ;
  int result;
  
  result = (int)(0x18081000);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_channel_t_gpionum_set(void * jarg1, int jarg2) {
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  int arg2 ;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->gpionum = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ws2811_channel_t_gpionum_get(void * jarg1) {
  int jresult ;
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  int result;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  result = (int) ((arg1)->gpionum);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_channel_t_invert_set(void * jarg1, int jarg2) {
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  int arg2 ;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->invert = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ws2811_channel_t_invert_get(void * jarg1) {
  int jresult ;
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  int result;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  result = (int) ((arg1)->invert);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_channel_t_count_set(void * jarg1, int jarg2) {
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  int arg2 ;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->count = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ws2811_channel_t_count_get(void * jarg1) {
  int jresult ;
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  int result;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  result = (int) ((arg1)->count);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_channel_t_strip_type_set(void * jarg1, int jarg2) {
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  int arg2 ;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->strip_type = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ws2811_channel_t_strip_type_get(void * jarg1) {
  int jresult ;
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  int result;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  result = (int) ((arg1)->strip_type);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_channel_t_leds_set(void * jarg1, void * jarg2) {
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  ws2811_led_t *arg2 = (ws2811_led_t *) 0 ;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  arg2 = (ws2811_led_t *)jarg2; 
  if (arg1) (arg1)->leds = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ws2811_channel_t_leds_get(void * jarg1) {
  void * jresult ;
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  ws2811_led_t *result = 0 ;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  result = (ws2811_led_t *) ((arg1)->leds);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_channel_t_brightness_set(void * jarg1, unsigned char jarg2) {
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  uint8_t arg2 ;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  arg2 = (uint8_t)jarg2; 
  if (arg1) (arg1)->brightness = arg2;
}


SWIGEXPORT unsigned char SWIGSTDCALL CSharp_ws2811_channel_t_brightness_get(void * jarg1) {
  unsigned char jresult ;
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  uint8_t result;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  result = (uint8_t) ((arg1)->brightness);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_channel_t_wshift_set(void * jarg1, unsigned char jarg2) {
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  uint8_t arg2 ;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  arg2 = (uint8_t)jarg2; 
  if (arg1) (arg1)->wshift = arg2;
}


SWIGEXPORT unsigned char SWIGSTDCALL CSharp_ws2811_channel_t_wshift_get(void * jarg1) {
  unsigned char jresult ;
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  uint8_t result;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  result = (uint8_t) ((arg1)->wshift);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_channel_t_rshift_set(void * jarg1, unsigned char jarg2) {
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  uint8_t arg2 ;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  arg2 = (uint8_t)jarg2; 
  if (arg1) (arg1)->rshift = arg2;
}


SWIGEXPORT unsigned char SWIGSTDCALL CSharp_ws2811_channel_t_rshift_get(void * jarg1) {
  unsigned char jresult ;
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  uint8_t result;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  result = (uint8_t) ((arg1)->rshift);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_channel_t_gshift_set(void * jarg1, unsigned char jarg2) {
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  uint8_t arg2 ;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  arg2 = (uint8_t)jarg2; 
  if (arg1) (arg1)->gshift = arg2;
}


SWIGEXPORT unsigned char SWIGSTDCALL CSharp_ws2811_channel_t_gshift_get(void * jarg1) {
  unsigned char jresult ;
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  uint8_t result;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  result = (uint8_t) ((arg1)->gshift);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_channel_t_bshift_set(void * jarg1, unsigned char jarg2) {
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  uint8_t arg2 ;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  arg2 = (uint8_t)jarg2; 
  if (arg1) (arg1)->bshift = arg2;
}


SWIGEXPORT unsigned char SWIGSTDCALL CSharp_ws2811_channel_t_bshift_get(void * jarg1) {
  unsigned char jresult ;
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  uint8_t result;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  result = (uint8_t) ((arg1)->bshift);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_channel_t_gamma_set(void * jarg1, void * jarg2) {
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  uint8_t *arg2 = (uint8_t *) 0 ;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  arg2 = (uint8_t *)jarg2; 
  if (arg1) (arg1)->gamma = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ws2811_channel_t_gamma_get(void * jarg1) {
  void * jresult ;
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  uint8_t *result = 0 ;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  result = (uint8_t *) ((arg1)->gamma);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_ws2811_channel_t() {
  void * jresult ;
  ws2811_channel_t *result = 0 ;
  
  result = (ws2811_channel_t *)calloc(1, sizeof(ws2811_channel_t));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_ws2811_channel_t(void * jarg1) {
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_t_render_wait_time_set(void * jarg1, unsigned long long jarg2) {
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  uint64_t arg2 ;
  
  arg1 = (ws2811_t *)jarg1; 
  arg2 = (uint64_t)jarg2; 
  if (arg1) (arg1)->render_wait_time = arg2;
}


SWIGEXPORT unsigned long long SWIGSTDCALL CSharp_ws2811_t_render_wait_time_get(void * jarg1) {
  unsigned long long jresult ;
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  uint64_t result;
  
  arg1 = (ws2811_t *)jarg1; 
  result = (uint64_t) ((arg1)->render_wait_time);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_t_device_set(void * jarg1, void * jarg2) {
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  struct ws2811_device *arg2 = (struct ws2811_device *) 0 ;
  
  arg1 = (ws2811_t *)jarg1; 
  arg2 = (struct ws2811_device *)jarg2; 
  if (arg1) (arg1)->device = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ws2811_t_device_get(void * jarg1) {
  void * jresult ;
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  struct ws2811_device *result = 0 ;
  
  arg1 = (ws2811_t *)jarg1; 
  result = (struct ws2811_device *) ((arg1)->device);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_t_rpi_hw_set(void * jarg1, void * jarg2) {
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  rpi_hw_t *arg2 = (rpi_hw_t *) 0 ;
  
  arg1 = (ws2811_t *)jarg1; 
  arg2 = (rpi_hw_t *)jarg2; 
  if (arg1) (arg1)->rpi_hw = (rpi_hw_t const *)arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ws2811_t_rpi_hw_get(void * jarg1) {
  void * jresult ;
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  rpi_hw_t *result = 0 ;
  
  arg1 = (ws2811_t *)jarg1; 
  result = (rpi_hw_t *) ((arg1)->rpi_hw);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_t_freq_set(void * jarg1, unsigned int jarg2) {
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  uint32_t arg2 ;
  
  arg1 = (ws2811_t *)jarg1; 
  arg2 = (uint32_t)jarg2; 
  if (arg1) (arg1)->freq = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ws2811_t_freq_get(void * jarg1) {
  unsigned int jresult ;
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  uint32_t result;
  
  arg1 = (ws2811_t *)jarg1; 
  result = (uint32_t) ((arg1)->freq);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_t_dmanum_set(void * jarg1, int jarg2) {
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  int arg2 ;
  
  arg1 = (ws2811_t *)jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->dmanum = arg2;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ws2811_t_dmanum_get(void * jarg1) {
  int jresult ;
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  int result;
  
  arg1 = (ws2811_t *)jarg1; 
  result = (int) ((arg1)->dmanum);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_t_channel_set(void * jarg1, void * jarg2) {
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  ws2811_channel_t *arg2 ;
  
  arg1 = (ws2811_t *)jarg1; 
  arg2 = (ws2811_channel_t *)jarg2; 
  {
    size_t ii;
    ws2811_channel_t *b = (ws2811_channel_t *) arg1->channel;
    for (ii = 0; ii < (size_t)RPI_PWM_CHANNELS; ii++) b[ii] = *((ws2811_channel_t *) arg2 + ii);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ws2811_t_channel_get(void * jarg1) {
  void * jresult ;
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  ws2811_channel_t *result = 0 ;
  
  arg1 = (ws2811_t *)jarg1; 
  result = (ws2811_channel_t *)(ws2811_channel_t *) ((arg1)->channel);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_ws2811_t() {
  void * jresult ;
  ws2811_t *result = 0 ;
  
  result = (ws2811_t *)calloc(1, sizeof(ws2811_t));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_ws2811_t(void * jarg1) {
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  
  arg1 = (ws2811_t *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_ws2811_init(void * jarg1) {
  int jresult ;
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  ws2811_return_t result;
  
  arg1 = (ws2811_t *)jarg1; 
  result = (ws2811_return_t)ws2811_init(arg1);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_ws2811_fini(void * jarg1) {
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  
  arg1 = (ws2811_t *)jarg1; 
  ws2811_fini(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_ws2811_render(void * jarg1) {
  int jresult ;
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  ws2811_return_t result;
  
  arg1 = (ws2811_t *)jarg1; 
  result = (ws2811_return_t)ws2811_render(arg1);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ws2811_wait(void * jarg1) {
  int jresult ;
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  ws2811_return_t result;
  
  arg1 = (ws2811_t *)jarg1; 
  result = (ws2811_return_t)ws2811_wait(arg1);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_ws2811_get_return_t_str(int jarg1) {
  char * jresult ;
  ws2811_return_t arg1 ;
  char *result = 0 ;
  
  arg1 = (ws2811_return_t)jarg1; 
  result = (char *)ws2811_get_return_t_str(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_ws2811_led_get(void * jarg1, int jarg2) {
  unsigned int jresult ;
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  int arg2 ;
  uint32_t result;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  arg2 = (int)jarg2; 
  result = (uint32_t)ws2811_led_get(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_ws2811_led_set(void * jarg1, int jarg2, unsigned int jarg3) {
  int jresult ;
  ws2811_channel_t *arg1 = (ws2811_channel_t *) 0 ;
  int arg2 ;
  uint32_t arg3 ;
  int result;
  
  arg1 = (ws2811_channel_t *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (uint32_t)jarg3; 
  result = (int)ws2811_led_set(arg1,arg2,arg3);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_ws2811_channel_get(void * jarg1, int jarg2) {
  void * jresult ;
  ws2811_t *arg1 = (ws2811_t *) 0 ;
  int arg2 ;
  ws2811_channel_t *result = 0 ;
  
  arg1 = (ws2811_t *)jarg1; 
  arg2 = (int)jarg2; 
  result = (ws2811_channel_t *)ws2811_channel_get(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

